// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412190833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ToDoList.Models.ToDoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ToDoList.Models.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TargetDayTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ToDoItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ToDoList.Models.Call", b =>
                {
                    b.HasBaseType("ToDoList.Models.ToDoItem");

                    b.Property<string>("InvitedPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Items", t =>
                        {
                            t.Property("InvitedPerson")
                                .HasColumnName("Call_InvitedPerson");
                        });

                    b.HasDiscriminator().HasValue("Call");
                });

            modelBuilder.Entity("ToDoList.Models.DateOfBirth", b =>
                {
                    b.HasBaseType("ToDoList.Models.ToDoItem");

                    b.Property<string>("NameOfPersonWithDoB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DateOfBirth");
                });

            modelBuilder.Entity("ToDoList.Models.Meeting", b =>
                {
                    b.HasBaseType("ToDoList.Models.ToDoItem");

                    b.Property<string>("InvitedPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Meeting");
                });

            modelBuilder.Entity("ToDoList.Models.Task", b =>
                {
                    b.HasBaseType("ToDoList.Models.ToDoItem");

                    b.HasDiscriminator().HasValue("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
